services:
  n8n:
    container_name: n8n
    hostname: n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NODEJS_PREFER_IPV4=true
      - N8N_SECURE_COOKIE=false
      - N8N_PROTOCOL=http
    volumes:
      - $HOME/Documents/n8n_docker_files:/home/node/.n8n
    networks:
      - traefik_net
    command: "start --tunnel"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.docker.localhost`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.port=80"

networks:
  traefik_net:
    external: true
